# Generated by Django 4.2.2 on 2025-01-31 15:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=50)),
                ('email', models.EmailField(default=False, max_length=50, unique=True)),
                ('phone_number', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(10)])),
                ('subject', models.CharField(max_length=50)),
                ('message', models.CharField(max_length=350)),
            ],
        ),
        migrations.AddField(
            model_name='mymodel',
            name='balance',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
