# Generated by Django 4.2.2 on 2025-02-01 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_data_mymodel_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymodel',
            name='balance',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
