# Generated by Django 4.2.2 on 2025-02-09 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_alter_mymodel_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='mymodel',
            name='requiset',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
