# Generated by Django 4.2.2 on 2025-02-10 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_mymodel_requiset'),
    ]

    operations = [
        migrations.AddField(
            model_name='mymodel',
            name='condition',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
