# Generated by Django 4.2.2 on 2025-02-10 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_mymodel_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymodel',
            name='condition',
            field=models.CharField(blank=True, default=0, max_length=50),
        ),
    ]
