# Generated by Django 4.2.2 on 2025-02-10 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_alter_mymodel_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymodel',
            name='condition',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
